// Code generated by "stringer -type=Tag -linecomment"; DO NOT EDIT.

package classify

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Code-1]
	_ = x[NoneCode-2]
	_ = x[Fix-3]
	_ = x[Bug-4]
	_ = x[Add-5]
	_ = x[Update-6]
	_ = x[Feature-7]
	_ = x[Tests-8]
	_ = x[Documentations-9]
	_ = x[Refactor-10]
	_ = x[License-11]
	_ = x[Build-12]
	_ = x[CI-13]
	_ = x[TechnicalDebt-14]
	_ = x[Style-15]
	_ = x[Release-16]
	_ = x[Dependencies-17]
	_ = x[GeneratedCode-18]
	_ = x[PerformanceImprovements-19]
	_ = x[Reverts-20]
	_ = x[MiscellaneousChores-21]
}

const _Tag_name = "CodeNone CodeFixBugAddUpdateFeatureTestsDocumentationsCode RefactoringLicenseBuild SystemContinuous IntegrationTechnical DebtStyleReleaseDependenciesGenerated CodePerformance ImprovementsRevertsMiscellaneous Chores"

var _Tag_index = [...]uint8{0, 4, 13, 16, 19, 22, 28, 35, 40, 54, 70, 77, 89, 111, 125, 130, 137, 149, 163, 187, 194, 214}

func (i Tag) String() string {
	i -= 1
	if i >= Tag(len(_Tag_index)-1) {
		return "Tag(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Tag_name[_Tag_index[i]:_Tag_index[i+1]]
}
