// Code generated by "stringer -type=Action -linecomment -trimprefix Action"; DO NOT EDIT.

package invoke

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionRepositoryAdded-1]
	_ = x[ActionRepositoryPush-2]
	_ = x[ActionRepositoryRecovering-3]
	_ = x[ActionRepositoryAdminTrigger-4]
	_ = x[ActionRepositoryRefreshing-5]
	_ = x[ActionPullRequestAdded-6]
	_ = x[ActionPullRequestUpdate-7]
	_ = x[ActionPullRequestRecovering-8]
	_ = x[ActionPullRequestAdminTrigger-9]
	_ = x[ActionPullRequestRefreshing-10]
	_ = x[ActionPushCheck-11]
	_ = x[ActionPullRequestCheck-12]
	_ = x[ActionMonitorRepository-13]
}

const _Action_name = "Repository addRepository pushRepository recoverRepository admin triggerRepository refreshPull request addPull request updatePull request recoverPull request admin triggerPull request refreshPushCheckPullRequestCheckMonitor repository"

var _Action_index = [...]uint8{0, 14, 29, 47, 71, 89, 105, 124, 144, 170, 190, 199, 215, 233}

func (i Action) String() string {
	i -= 1
	if i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
