// Code generated by "stringer -type=DeltaType -trimprefix=Delta -linecomment"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeltaDeleted - -1]
	_ = x[DeltaUnmodified-0]
	_ = x[DeltaAdded-1]
	_ = x[DeltaModified-2]
	_ = x[DeltaRenamed-3]
	_ = x[DeltaCopied-4]
	_ = x[DeltaIgnored-5]
	_ = x[DeltaUntracked-6]
	_ = x[DeltaTypeChange-7]
	_ = x[DeltaUnreadable-8]
	_ = x[DeltaConflicted-9]
	_ = x[DeltaOther-10]
}

const _DeltaType_name = "DeletedUnmodifiedAddedModifiedRenamedCopiedIgnoredUntrackedTypeChangeUnreadableConflictedOther"

var _DeltaType_index = [...]uint8{0, 7, 17, 22, 30, 37, 43, 50, 59, 69, 79, 89, 94}

func (i DeltaType) String() string {
	i -= -1
	if i < 0 || i >= DeltaType(len(_DeltaType_index)-1) {
		return "DeltaType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _DeltaType_name[_DeltaType_index[i]:_DeltaType_index[i+1]]
}
