// Code generated by "stringer -type=Stage -linecomment"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Queued-0]
	_ = x[Added-1]
	_ = x[Cloning-2]
	_ = x[Cloned-3]
	_ = x[Fetching-4]
	_ = x[Fetched-5]
	_ = x[Ingesting-6]
	_ = x[Ingested-7]
	_ = x[Analyzing-8]
	_ = x[Analyzed-9]
	_ = x[Predicting-10]
	_ = x[Predicted-11]
	_ = x[Ready-12]
	_ = x[Failed-13]
	_ = x[Canceled-14]
	_ = x[Watched-15]
	_ = x[Recovered-16]
	_ = x[Ignored-17]
	_ = x[Progressing-18]
}

const _Stage_name = "QueuedAddedCloningClonedFetchingFetchedIngestingIngestedAnalyzingAnalyzedPredictingPredictedReadyFailedCanceledWatchedRecoveredIgnoredProgressing"

var _Stage_index = [...]uint8{0, 6, 11, 18, 24, 32, 39, 48, 56, 65, 73, 83, 92, 97, 103, 111, 118, 127, 134, 145}

func (i Stage) String() string {
	if i >= Stage(len(_Stage_index)-1) {
		return "Stage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stage_name[_Stage_index[i]:_Stage_index[i+1]]
}
