// Code generated by "stringer -type=Reason -linecomment"; DO NOT EDIT.

package insights

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DevFirstCommit-1]
	_ = x[ManyDevelopers-2]
	_ = x[FirstModification-3]
	_ = x[CommitLargeFiles-4]
	_ = x[DevNewToRepository-5]
	_ = x[DevNewToSubsystem-6]
	_ = x[DevIsLastModifier-7]
	_ = x[DevExpert-8]
	_ = x[FilesDevNew-9]
	_ = x[FilesDevExpert-10]
	_ = x[FilesFrequentlyChanged-11]
	_ = x[FilesFrequentlyFixed-12]
	_ = x[FilesFrequentlyBuggy-13]
	_ = x[FilesAbandoned-14]
	_ = x[FilesRecentlyModified-15]
	_ = x[CommitScattered-16]
	_ = x[CommitIsLargest-17]
	_ = x[CommitIsLargestAdd-18]
	_ = x[CommitIsLargestDelete-19]
}

const _Reason_name = "DevFirstCommitManyDevelopersFirstModificationCommitLargeFilesDevNewToRepositoryDevNewToSubsystemDevIsLastModifierDevExpertFilesDevNewFilesDevExpertFilesFrequentlyChangedFilesFrequentlyFixedFilesFrequentlyBuggyFilesAbandonedFilesRecentlyModifiedCommitScatteredCommitIsLargestCommitIsLargestAddCommitIsLargestDelete"

var _Reason_index = [...]uint16{0, 14, 28, 45, 61, 79, 96, 113, 122, 133, 147, 169, 189, 209, 223, 244, 259, 274, 292, 313}

func (i Reason) String() string {
	i -= 1
	if i < 0 || i >= Reason(len(_Reason_index)-1) {
		return "Reason(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Reason_name[_Reason_index[i]:_Reason_index[i+1]]
}
