// Code generated by "stringer -type=Stage -linecomment -trimprefix Stage"; DO NOT EDIT.

package ml

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StageDataPreparation-1]
	_ = x[StageDataSplitting-2]
	_ = x[StageModelBuilding-3]
	_ = x[StagePredicting-4]
	_ = x[StageQuantileCalculation-5]
}

const _Stage_name = "data preparationdata splittingmodel buildingpredictingquantile calculation"

var _Stage_index = [...]uint8{0, 16, 30, 44, 54, 74}

func (i Stage) String() string {
	i -= 1
	if i >= Stage(len(_Stage_index)-1) {
		return "Stage(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Stage_name[_Stage_index[i]:_Stage_index[i+1]]
}
